#!/usr/bin/env bash

HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

VERSIONS=("5.6" "7.0" "7.1" "7.2")

for i in "${!VERSIONS[@]}"; do
    docker build -f "${HOME}/${VERSIONS[$i]}/fpm/alpine/Dockerfile" \
        -t "freeyland-m2c-php-fpm-${VERSIONS[$i]}-alpine" \
        "${HOME}"
    docker tag "freeyland-m2c-php-fpm-${VERSIONS[$i]}-alpine" \
        "freeyland/m2c:php-fpm-${VERSIONS[$i]}-alpine"

    docker build -f "${HOME}/${VERSIONS[$i]}/fpm-xdebug/alpine/Dockerfile" \
        -t "freeyland-m2c-php-fpm-${VERSIONS[$i]}-xdebug-alpine" \
        "${HOME}"
    docker tag "freeyland-m2c-php-fpm-${VERSIONS[$i]}-xdebug-alpine" \
        "freeyland/m2c:php-fpm-${VERSIONS[$i]}-xdebug-alpine"
done

rm -rf "${HOME}/.docker"

# Due to docker error "denied: requested access to the resource is denied",
# echoing commands to run them manually instead of running directly
echo

for i in "${!VERSIONS[@]}"; do
    echo "docker push \"freeyland/m2c:php-fpm-${VERSIONS[$i]}-alpine\""
    echo "docker rmi -f \"freeyland/m2c:php-fpm-${VERSIONS[$i]}-alpine\""
    echo "docker push \"freeyland/m2c:php-fpm-${VERSIONS[$i]}-xdebug-alpine\""
    echo "docker rmi -f \"freeyland/m2c:php-fpm-${VERSIONS[$i]}-xdebug-alpine\""
done
