version: "3.5"

services:
  nginx:
    container_name: ${M2C_CFG_DOMAIN_NAME}__nginx
    hostname: ${M2C_CFG_DOMAIN_NAME}__nginx
    image: freeyland/e2c:nginx-${M2C_CFG_NGINX:-1.17}-alpine
    depends_on:
      - db
      - php

  varnish:
    container_name: ${M2C_CFG_DOMAIN_NAME}__varnish
    hostname: ${M2C_CFG_DOMAIN_NAME}__varnish
    image: freeyland/e2c:varnish-${M2C_CFG_VARNISH:-5.2}-alpine
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${M2C_CFG_DOMAIN_NAME}
    networks:
      - m2c
      - default
