version: "3.5"

services:
  elasticsearch:
    container_name: ${M2C_CFG_DOMAIN_NAME}__elasticsearch
    hostname: ${M2C_CFG_DOMAIN_NAME}__elasticsearch
    image: freeyland/m2c:elasticsearch-${M2C_CFG_ELASTICSEARCH:-6.8}-alpine
    user: root
    labels:
      - traefik.enable=true
      - traefik.port=9200
      - traefik.frontend.rule=Host:elasticsearch.${M2C_CFG_DOMAIN_NAME}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - m2c
      - default

volumes: elasticsearch_data:
