version: "3.5"

services:
  nginx:
    container_name: ${M2C_CFG_DOMAIN_NAME}__nginx
    hostname: ${M2C_CFG_DOMAIN_NAME}__nginx
    image: freeyland/m2c:nginx-${M2C_CFG_NGINX:-1.17}-alpine
    depends_on:
      - db
      - php
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${M2C_CFG_DOMAIN_NAME}
    networks:
      - m2c
      - default
