version: "3.5"

services:
  nginx:
    container_name: ${E2C_CFG_DOMAIN_NAME}__nginx
    hostname: ${E2C_CFG_DOMAIN_NAME}__nginx
    image: freeyland/e2c:nginx-${E2C_CFG_NGINX:-1.17}-alpine
    depends_on:
      - db
      - php
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${E2C_CFG_DOMAIN_NAME}
    networks:
      - e2c
      - default
