#!/usr/bin/env bash

HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

VERSIONS=("4.1" "5.2")

for i in "${!VERSIONS[@]}"; do
    docker build -t "emma2click/e2c:varnish-${VERSIONS[$i]}-alpine" \
        "${HOME}/${VERSIONS[$i]}/alpine/"

    docker tag "emma2click/e2c:varnish-${VERSIONS[$i]}-alpine" \
        "emma2click/e2c:varnish-${VERSIONS[$i]}-alpine"
done

rm -rf "${HOME}/.docker"

# Due to docker error "denied: requested access to the resource is denied",
# echoing commands to run them manually instead of running directly
echo

for i in "${!VERSIONS[@]}"; do
    echo "docker push \"emma2click/e2c:varnish-${VERSIONS[$i]}-alpine\""
    echo "docker rmi -f \"emma2click/e2c:varnish-${VERSIONS[$i]}-alpine\""
done
