version: "3.5"

services:
  nginx:
    container_name: ${E2C_CFG_DOMAIN_NAME}__nginx
    hostname: ${E2C_CFG_DOMAIN_NAME}__nginx
    image: emma2click/e2c:nginx-${E2C_CFG_NGINX:-1.17}-alpine
    depends_on:
      - db
      - php

  varnish:
    container_name: ${E2C_CFG_DOMAIN_NAME}__varnish
    hostname: ${E2C_CFG_DOMAIN_NAME}__varnish
    image: emma2click/e2c:varnish-${E2C_CFG_VARNISH:-5.2}-alpine
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${E2C_CFG_DOMAIN_NAME}
    networks:
      - e2c
      - default
