#!/usr/bin/env bash

HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

VERSIONS=("1.17")
#VERSIONS=( "1.12" "1.13" "1.14" "1.15" "1.16" "1.17")

for i in "${!VERSIONS[@]}"; do
    echo "---------------------------------------------------------------   Building for ${VERSIONS[$i]}"
    docker build --build-arg NGINX_VERSION="${VERSIONS[$i]}" \
        -t "freeyland/e2c:nginx-${VERSIONS[$i]}-alpine" "${HOME}/alpine/"
    docker tag "freeyland/e2c:nginx-${VERSIONS[$i]}-alpine" \
        "freeyland/e2c:nginx-${VERSIONS[$i]}-alpine"
done

rm -rf "${HOME}/.docker"

# Due to docker error "denied: requested access to the resource is denied",
# echoing commands to run them manually instead of running directly
echo

for i in "${!VERSIONS[@]}"; do
    echo "docker push \"freeyland/e2c:nginx-${VERSIONS[$i]}-alpine\""
done

for i in "${!VERSIONS[@]}"; do
    echo "docker rmi -f \"freeyland/e2c:nginx-${VERSIONS[$i]}-alpine\""
done
