version: "3.5"

services:
  emma2click:
    container_name: e2c.test__emma2click
    image: nginx:1.17-alpine
    volumes:
      - ~/.m2c/www/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.m2c/www/html/index.html:/usr/share/nginx/html/index.html
    labels:
      - traefik.passHostHeader=true
      - traefik.enable=true
      - traefik.frontend.rule=Host:m2c.test
      - traefik.port=8080
    restart: always

  traefik:
    container_name: e2c.test__traefik
    image: traefik:1.7-alpine
    command:
      - --api
      - --docker
      - --docker.domain=test
      - --docker.network=m2c
      - --docker.exposedByDefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/.m2c/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ~/.m2c/ssl/certs/m2c.crt:/etc/ssl/certs/m2c.crt:ro
      - ~/.m2c/ssl/private/m2c.key:/etc/ssl/private/m2c.key:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.m2c.test
      - traefik.port=8080
    restart: always

  portainer:
    container_name: e2c.test__portainer
    image: portainer/portainer:1.22.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:portainer.m2c.test
      - traefik.port=9000
    restart: always

  mailhog:
    container_name: e2c.test__mailhog
    hostname: mailhog
    image: mailhog/mailhog:v1.0.0
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mailhog.m2c.test
      - traefik.port=8025
    restart: always

  dnsmasq:
    container_name: e2c.test__dnsmasq
    image: jpillora/dnsmasq:1.1
    ports:
      - 53:53/udp
    volumes:
      - ~/.m2c/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dnsmasq.m2c.test
      - traefik.port=8080
    restart: always

volumes:
  portainer:

networks:
  default:
    name: e2c
